/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.text.DecimalFormat;
import javax.swing.*;

/**
 *
 * @author 0dr4c1r
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMicro = new javax.swing.JToggleButton();
        btnMacro = new javax.swing.JToggleButton();
        lblTitulo = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMicro.setText("MICRO");
        btnMicro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMicroActionPerformed(evt);
            }
        });

        btnMacro.setText("MACRO");
        btnMacro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMacroActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblTitulo.setText("Macroeconomia");

        btnCalc.setText("<html>\n<center>\nCalculadora de retorno de<br>\ninvestimento em tesouro direto\n</center>\n</html>");
        btnCalc.setActionCommand("<html>\n      Calculadora de retorno de<br>\n investimento em tesouro direto\n</html>");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnMicro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(263, 263, 263))))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(266, 266, 266)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMicro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMacroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMacroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        TelaMacro telaMacro = new TelaMacro();
        telaMacro.setVisible(true);
    }//GEN-LAST:event_btnMacroActionPerformed

    private void btnMicroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMicroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        TelaMicro telaMicro = new TelaMicro();
        telaMicro.setVisible(true);
    }//GEN-LAST:event_btnMicroActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        JTextField inAporte = new JTextField(5);
        JTextField inPrazo = new JTextField(5);
        JTextField inTaxaSelic = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Valor investido: R$"));
        myPanel.add(inAporte);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Prazo:"));
        myPanel.add(inPrazo);
        myPanel.add(new JLabel("ano(s)"));
        myPanel.add(Box.createHorizontalStrut(15));
        myPanel.add(new JLabel("Taxa Selic:"));
        myPanel.add(inTaxaSelic);
        myPanel.add(new JLabel("%"));

        double aporte = 0;
        double prazo = 0;
        double saldoFinal = 0;
        double taxaSelic = 0;

        try {
            int result = JOptionPane.showConfirmDialog(null, myPanel,
                    "Calculadora de Tesouro Direto", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {
                aporte = Double.parseDouble(inAporte.getText());
                prazo = Double.parseDouble(inPrazo.getText());
                taxaSelic = Double.parseDouble(inTaxaSelic.getText());
                saldoFinal = aporte;
            }

            for (int i = 0; i < prazo; i++) {
                saldoFinal += saldoFinal * (taxaSelic / 100);
            }
            JOptionPane.showMessageDialog(null, "Saldo final: R$" + new DecimalFormat("##.##").format(saldoFinal));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Formato inválido! Insira novamente com apenas números separados por ponto.");
        }
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JToggleButton btnMacro;
    private javax.swing.JToggleButton btnMicro;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
